// <auto-generated />
namespace Zidium.Storage.Ef.Migrations.PostgreSql
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ChangedMetricHistoryIndexForHistoryDeletion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ChangedMetricHistoryIndexForHistoryDeletion));
        
        string IMigrationMetadata.Id
        {
            get { return "201806092012515_ChangedMetricHistoryIndexForHistoryDeletion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
