// <auto-generated />
namespace Zidium.Storage.Ef.Migrations.MsSql
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddTcpPortRules : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddTcpPortRules));
        
        string IMigrationMetadata.Id
        {
            get { return "201909201752164_AddTcpPortRules"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
