// <auto-generated />
namespace Zidium.Storage.Ef.Migrations.MsSql
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class FixVirusTotal : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixVirusTotal));
        
        string IMigrationMetadata.Id
        {
            get { return "202002061507069_FixVirusTotal"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
