// <auto-generated />
namespace Zidium.Storage.Ef.Migrations.MsSql
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class VirusTotal : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(VirusTotal));
        
        string IMigrationMetadata.Id
        {
            get { return "202001232048399_VirusTotal"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
