// <auto-generated />
namespace Zidium.Core.AccountsDb.Migrations.MsSql
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class OpenSource1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OpenSource1));
        
        string IMigrationMetadata.Id
        {
            get { return "201803221045092_OpenSource1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
