// <auto-generated />
namespace Zidium.Core.AccountsDb.Migrations.MsSql
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class SendMessageCommandTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SendMessageCommandTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202001141705124_SendMessageCommandTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
