#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\AccountInfo\Index.cshtml"
    using Zidium.UserAccount;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/AccountInfo/Index.cshtml")]
    public partial class _Views_AccountInfo_Index_cshtml : System.Web.Mvc.WebViewPage<Zidium.UserAccount.Models.ShowAccountModel>
    {
        public _Views_AccountInfo_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\Views\AccountInfo\Index.cshtml"
  
    ViewBag.Title = "Аккаунт";
    ViewBag.ActiveMenuItems = "Manage,Account";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 9 "..\..\Views\AccountInfo\Index.cshtml"
Write(Html.Partial("_PageTitle"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"bottom20px\"");

WriteLiteral(">\r\n    <p>\r\n        <span");

WriteLiteral(" class=\"simple-text-header\"");

WriteLiteral(">Имя аккаунта: </span>\r\n        <span");

WriteLiteral(" class=\"simple-text-value\"");

WriteLiteral(">");

            
            #line 14 "..\..\Views\AccountInfo\Index.cshtml"
                                   Write(Model.AccountName);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n    </p>\r\n\r\n");

            
            #line 17 "..\..\Views\AccountInfo\Index.cshtml"
    
            
            #line default
            #line hidden
            
            #line 17 "..\..\Views\AccountInfo\Index.cshtml"
     if (UserHelper.CurrentUser.CanEditCommonData())
    {

            
            #line default
            #line hidden
WriteLiteral("        <p>\r\n            <span");

WriteLiteral(" class=\"simple-text-header\"");

WriteLiteral(">Секретный ключ API: </span>\r\n            <span");

WriteLiteral(" class=\"simple-text-value collapse\"");

WriteLiteral(" id=\"apiSecretKey\"");

WriteLiteral(">");

            
            #line 21 "..\..\Views\AccountInfo\Index.cshtml"
                                                                  Write(Model.SecretKey);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(" id=\"showApiKey\"");

WriteLiteral(">Показать</a>\r\n            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"btn btn-default collapse space-left\"");

WriteLiteral(" id=\"hideApiKey\"");

WriteLiteral(">Скрыть</a>\r\n        </p>\r\n");

            
            #line 25 "..\..\Views\AccountInfo\Index.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n\r\n<hr />\r\n\r\n");

            
            #line 30 "..\..\Views\AccountInfo\Index.cshtml"
 if (UserHelper.CurrentUser.CanEditCommonData())
{

            
            #line default
            #line hidden
WriteLiteral(@"    <script>
        $(function () {

            // показываем ключ API
            $(""#showApiKey, #hideApiKey"")
                .click(function (event) {
                    event.preventDefault();
                    $(""#apiSecretKey"").toggle();
                    $(""#showApiKey"").toggle();
                    $(""#hideApiKey"").toggle();
                });
        })
    </script>
");

            
            #line 45 "..\..\Views\AccountInfo\Index.cshtml"
}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
